export const prompts = [
    "fake moon landing",
    "80% certain",
    "large hadron collider",
    "second date",
    "starry night",
    "LSD trip",
    "colonizing mars",
    "friendly couchsurfer",
    "missed high five",
    "Harambe The Pirate Gorilla",
    "Embarassing childhood memories",
    "Banks with tanks",
    "Magic internet money",
    "Alligator eating ice cream",
    "Confused cat",
    "Muslim Mona Lisa",
    "Arnold Schwartznegger",
    "Meme economy",
    "Cremino vs Croccante",
    "La Sfinge",
    "Karl Marx birthday",
    "Triple rainbow",
    "La terra promessa",
    "Mirror",
    "Running dog",
    "Leopards saving the city",
    "Orzo Bruno",
    "confused eggplant",
    "Empathy",
    "Ancient Greece",
    "La stanza più remota della torre più alta",
    "Bread stapled to a tree",
    "Elon musk children",
    "Portare a spasso tartaruga",
    "passeggiare a Pisa con una pecora",
    "parrucchiere che si finge idraulico",
    "mouth full of marbles",
    "dumplings",
    "salsa di soia",
    "tiny tiny sled dogs",
    "french jedi",
    "purse full of dreams",
    "life spiraling out of control",
    "planet of the babies",
    "I'm not so sure about this hitchhiker",
    "imposter",
    "practice kiss",
    "social media manager",
    "new years resolution",
    "End of quarantena party",
    "Playing with spoons",
    "Poisoned toothpaste",
    "Giant cat",
    "a wheelchair for six",
    "trump fart",
    "pubblicità della tim",
    "parrucchiere di mattarella",
    "il cuore immacolato di maria",
    "autocertificazione",
    "lavatrice occupata",
    "hercules",
    "constipated harry potter"
]